import { figma, jsx } from "@figma/code-connect/react"
import * as React from "react"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/rgqHmkJX2Uw9PhGoon1OIh/MCP-Code-Connect-DS?node-id=28-1289&m=dev",
  {
    props: {
      buttonText: "Button",
      variant: "Default",
      size: "default",
      state: "Default",
      showLeftIcon: false,
      showRightIcon: false
    },
    example: (props: any) => {
      const buttonText = props.buttonText || "Button";
      return React.createElement('button', {
        className: "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground shadow-xs hover:bg-primary/90 h-9 px-4 py-2",
        children: buttonText
      });
    },
  },
)
