import { figma, html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 * 
 * Note: The published code from this component is available in the bottom right panel
 * of the application when the "Show Published Code" button is clicked.
 */

figma.connect(
  "https://www.figma.com/design/rgqHmkJX2Uw9PhGoon1OIh/MCP-Code-Connect-DS?node-id=12-65&m=dev",
  {
    props: {
      buttonText: "Button",
      variant: "Default",
      size: "default",
      state: "Default"
    },
    example: (props) => {
      const buttonText = props.buttonText || "Button";
      const variant = props.variant || "Default";
      
      // Simple variant mapping
      let className = "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 h-9 px-4 py-2";
      
      if (variant === "Default") {
        className += " bg-primary text-primary-foreground shadow-xs hover:bg-primary/90";
      } else if (variant === "Secondary") {
        className += " bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80";
      } else if (variant === "Destructive") {
        className += " bg-destructive text-white shadow-xs hover:bg-destructive/90";
      } else if (variant === "Outline") {
        className += " border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground";
      } else if (variant === "Ghost") {
        className += " hover:bg-accent hover:text-accent-foreground";
      } else if (variant === "Link") {
        className += " text-primary underline-offset-4 hover:underline";
      }
      
      return html`
        <button class="${className}">
          ${buttonText}
        </button>
      `;
    },
  },
)
