import { figma, html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/rgqHmkJX2Uw9PhGoon1OIh/MCP-Code-Connect-DS?node-id=12-272&m=dev",
  {
    props: {
      label: "Your message",
      helperText: "Type your message here"
    },
    example: (props) => html`
      <div class="flex flex-col gap-2">
        <label class="font-['Inter:Medium',_sans-serif] font-medium text-[#000000] text-[14px] leading-[14px]">
          ${props.label || "Your message"}
        </label>
        <textarea
          class="border-input placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 flex field-sizing-content min-h-16 w-full rounded-md border bg-transparent px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
          placeholder="${props.helperText || "Type your message here"}"
        />
      </div>
    `,
  },
) 